### PR TITLE
Add Keycloak guide

### PR DESCRIPTION
**Pull request by Sherex**
Hello,

I created this guide for Keycloak a while ago (I didn't realise there was a docs repo) and posted it as a [gist here](https://gist.github.com/Sherex/283d1e4ef07b2bf0a930417dc0117238) and on the [feature tracker](https://requarks.canny.io/wiki/p/keycloak-auth-docs-proposal-for-a-guide-written).

I added the image tag at the bottom for a Keycloak logo pointing to `https://static.requarks.io/logo/keycloak.svg`, let me know if I should remove it. :)

### CODE REVIEW

**Comment by chikamichi** [comment]
Terrific! I'd suggest adding a link to the guide though, maybe on https://github.com/Requarks/wiki-docs/blob/master/auth.md :shrug:  (there is this unlinked _Generic OpenID / Oauth2_ item in the _Modules_ list, which could be a good candidate; or adding an item altogether such as _Keycloak OpenID Connect_).

**Comment by Sherex** [comment]
Ah that's probably smart :P

I added it as it's own section as there are some very specific points that are for Keycloak.
But I created a generic one too here: #30

Let me know if something should be changed :)

**Comment by chikamichi** [comment]
Hopefully NGPixel will come by and validate some pending PR soon (or delegate to someone else?) :)

**Review by NGPixel — APPROVED** [review]

**Comment by chikamichi** [comment]
Thanks! Both of you :) :pray:

**Pull request merged**
